// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: dfs.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // Optional, not used in the new protocol.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type UploadFileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DataKeeperAddress string                 `protobuf:"bytes,2,opt,name=data_keeper_address,json=dataKeeperAddress,proto3" json:"data_keeper_address,omitempty"`
	DataKeeperPort    string                 `protobuf:"bytes,3,opt,name=data_keeper_port,json=dataKeeperPort,proto3" json:"data_keeper_port,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadFileResponse) GetDataKeeperAddress() string {
	if x != nil {
		return x.DataKeeperAddress
	}
	return ""
}

func (x *UploadFileResponse) GetDataKeeperPort() string {
	if x != nil {
		return x.DataKeeperPort
	}
	return ""
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DownloadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available data keeper download endpoints (host:download_port).
	DataKeeperAddresses []string `protobuf:"bytes,1,rep,name=data_keeper_addresses,json=dataKeeperAddresses,proto3" json:"data_keeper_addresses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadFileResponse) GetDataKeeperAddresses() []string {
	if x != nil {
		return x.DataKeeperAddresses
	}
	return nil
}

type FileTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestinationIp string                 `protobuf:"bytes,2,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferRequest) Reset() {
	*x = FileTransferRequest{}
	mi := &file_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferRequest) ProtoMessage() {}

func (x *FileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferRequest.ProtoReflect.Descriptor instead.
func (*FileTransferRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *FileTransferRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *FileTransferRequest) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *FileTransferRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type FileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResponse) Reset() {
	*x = FileTransferResponse{}
	mi := &file_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResponse) ProtoMessage() {}

func (x *FileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResponse.ProtoReflect.Descriptor instead.
func (*FileTransferResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *FileTransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

type GetFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filenames     []string               `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListResponse) Reset() {
	*x = GetFileListResponse{}
	mi := &file_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListResponse) ProtoMessage() {}

func (x *GetFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListResponse.ProtoReflect.Descriptor instead.
func (*GetFileListResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileListResponse) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterDataKeeperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	DataPort      string                 `protobuf:"bytes,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"`
	DownloadPort  string                 `protobuf:"bytes,3,opt,name=download_port,json=downloadPort,proto3" json:"download_port,omitempty"` // New field for the separate download listener port.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataKeeperRequest) Reset() {
	*x = RegisterDataKeeperRequest{}
	mi := &file_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataKeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataKeeperRequest) ProtoMessage() {}

func (x *RegisterDataKeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataKeeperRequest.ProtoReflect.Descriptor instead.
func (*RegisterDataKeeperRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterDataKeeperRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterDataKeeperRequest) GetDataPort() string {
	if x != nil {
		return x.DataPort
	}
	return ""
}

func (x *RegisterDataKeeperRequest) GetDownloadPort() string {
	if x != nil {
		return x.DownloadPort
	}
	return ""
}

type RegisterDataKeeperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDataKeeperResponse) Reset() {
	*x = RegisterDataKeeperResponse{}
	mi := &file_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDataKeeperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataKeeperResponse) ProtoMessage() {}

func (x *RegisterDataKeeperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataKeeperResponse.ProtoReflect.Descriptor instead.
func (*RegisterDataKeeperResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterDataKeeperResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FileUploadedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	DataKeeper    string                 `protobuf:"bytes,2,opt,name=data_keeper,json=dataKeeper,proto3" json:"data_keeper,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadedRequest) Reset() {
	*x = FileUploadedRequest{}
	mi := &file_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadedRequest) ProtoMessage() {}

func (x *FileUploadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadedRequest.ProtoReflect.Descriptor instead.
func (*FileUploadedRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *FileUploadedRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadedRequest) GetDataKeeper() string {
	if x != nil {
		return x.DataKeeper
	}
	return ""
}

func (x *FileUploadedRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type FileUploadedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadedResponse) Reset() {
	*x = FileUploadedResponse{}
	mi := &file_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadedResponse) ProtoMessage() {}

func (x *FileUploadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadedResponse.ProtoReflect.Descriptor instead.
func (*FileUploadedResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *FileUploadedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUploadDataKeeperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadDataKeeperRequest) Reset() {
	*x = GetUploadDataKeeperRequest{}
	mi := &file_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadDataKeeperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadDataKeeperRequest) ProtoMessage() {}

func (x *GetUploadDataKeeperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadDataKeeperRequest.ProtoReflect.Descriptor instead.
func (*GetUploadDataKeeperRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{14}
}

type GetUploadDataKeeperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	DataPort      string                 `protobuf:"bytes,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadDataKeeperResponse) Reset() {
	*x = GetUploadDataKeeperResponse{}
	mi := &file_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadDataKeeperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadDataKeeperResponse) ProtoMessage() {}

func (x *GetUploadDataKeeperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadDataKeeperResponse.ProtoReflect.Descriptor instead.
func (*GetUploadDataKeeperResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *GetUploadDataKeeperResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetUploadDataKeeperResponse) GetDataPort() string {
	if x != nil {
		return x.DataPort
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *GetFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{17}
}

func (x *GetFileResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type ReplicateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateFileRequest) Reset() {
	*x = ReplicateFileRequest{}
	mi := &file_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateFileRequest) ProtoMessage() {}

func (x *ReplicateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateFileRequest.ProtoReflect.Descriptor instead.
func (*ReplicateFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *ReplicateFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReplicateFileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

var File_dfs_proto protoreflect.FileDescriptor

const file_dfs_proto_rawDesc = "" +
	"\n" +
	"\tdfs.proto\x12\x03dfs\"L\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"\x86\x01\n" +
	"\x12UploadFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12.\n" +
	"\x13data_keeper_address\x18\x02 \x01(\tR\x11dataKeeperAddress\x12(\n" +
	"\x10data_keeper_port\x18\x03 \x01(\tR\x0edataKeeperPort\"1\n" +
	"\x13DownloadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"J\n" +
	"\x14DownloadFileResponse\x122\n" +
	"\x15data_keeper_addresses\x18\x01 \x03(\tR\x13dataKeeperAddresses\"v\n" +
	"\x13FileTransferRequest\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12%\n" +
	"\x0edestination_ip\x18\x02 \x01(\tR\rdestinationIp\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\".\n" +
	"\x14FileTransferResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x14\n" +
	"\x12GetFileListRequest\"3\n" +
	"\x13GetFileListResponse\x12\x1c\n" +
	"\tfilenames\x18\x01 \x03(\tR\tfilenames\",\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x19RegisterDataKeeperRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\tR\bdataPort\x12#\n" +
	"\rdownload_port\x18\x03 \x01(\tR\fdownloadPort\"6\n" +
	"\x1aRegisterDataKeeperResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x13FileUploadedRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vdata_keeper\x18\x02 \x01(\tR\n" +
	"dataKeeper\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\"0\n" +
	"\x14FileUploadedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1c\n" +
	"\x1aGetUploadDataKeeperRequest\"T\n" +
	"\x1bGetUploadDataKeeperResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\tR\bdataPort\",\n" +
	"\x0eGetFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\".\n" +
	"\x0fGetFileResponse\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\"O\n" +
	"\x14ReplicateFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData2\x87\x04\n" +
	"\rMasterTracker\x12=\n" +
	"\n" +
	"UploadFile\x12\x16.dfs.UploadFileRequest\x1a\x17.dfs.UploadFileResponse\x12C\n" +
	"\fDownloadFile\x12\x18.dfs.DownloadFileRequest\x1a\x19.dfs.DownloadFileResponse\x12@\n" +
	"\vGetFileList\x12\x17.dfs.GetFileListRequest\x1a\x18.dfs.GetFileListResponse\x12:\n" +
	"\tHeartbeat\x12\x15.dfs.HeartbeatRequest\x1a\x16.dfs.HeartbeatResponse\x12U\n" +
	"\x12RegisterDataKeeper\x12\x1e.dfs.RegisterDataKeeperRequest\x1a\x1f.dfs.RegisterDataKeeperResponse\x12C\n" +
	"\fFileUploaded\x12\x18.dfs.FileUploadedRequest\x1a\x19.dfs.FileUploadedResponse\x12X\n" +
	"\x13GetUploadDataKeeper\x12\x1f.dfs.GetUploadDataKeeperRequest\x1a .dfs.GetUploadDataKeeperResponse2\xce\x01\n" +
	"\n" +
	"DataKeeper\x12C\n" +
	"\fFileTransfer\x12\x18.dfs.FileTransferRequest\x1a\x19.dfs.FileTransferResponse\x124\n" +
	"\aGetFile\x12\x13.dfs.GetFileRequest\x1a\x14.dfs.GetFileResponse\x12E\n" +
	"\rReplicateFile\x12\x19.dfs.ReplicateFileRequest\x1a\x19.dfs.FileTransferResponseB\x16Z\x14./internal/grpc;grpcb\x06proto3"

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData []byte
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)))
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dfs_proto_goTypes = []any{
	(*UploadFileRequest)(nil),           // 0: dfs.UploadFileRequest
	(*UploadFileResponse)(nil),          // 1: dfs.UploadFileResponse
	(*DownloadFileRequest)(nil),         // 2: dfs.DownloadFileRequest
	(*DownloadFileResponse)(nil),        // 3: dfs.DownloadFileResponse
	(*FileTransferRequest)(nil),         // 4: dfs.FileTransferRequest
	(*FileTransferResponse)(nil),        // 5: dfs.FileTransferResponse
	(*GetFileListRequest)(nil),          // 6: dfs.GetFileListRequest
	(*GetFileListResponse)(nil),         // 7: dfs.GetFileListResponse
	(*HeartbeatRequest)(nil),            // 8: dfs.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 9: dfs.HeartbeatResponse
	(*RegisterDataKeeperRequest)(nil),   // 10: dfs.RegisterDataKeeperRequest
	(*RegisterDataKeeperResponse)(nil),  // 11: dfs.RegisterDataKeeperResponse
	(*FileUploadedRequest)(nil),         // 12: dfs.FileUploadedRequest
	(*FileUploadedResponse)(nil),        // 13: dfs.FileUploadedResponse
	(*GetUploadDataKeeperRequest)(nil),  // 14: dfs.GetUploadDataKeeperRequest
	(*GetUploadDataKeeperResponse)(nil), // 15: dfs.GetUploadDataKeeperResponse
	(*GetFileRequest)(nil),              // 16: dfs.GetFileRequest
	(*GetFileResponse)(nil),             // 17: dfs.GetFileResponse
	(*ReplicateFileRequest)(nil),        // 18: dfs.ReplicateFileRequest
}
var file_dfs_proto_depIdxs = []int32{
	0,  // 0: dfs.MasterTracker.UploadFile:input_type -> dfs.UploadFileRequest
	2,  // 1: dfs.MasterTracker.DownloadFile:input_type -> dfs.DownloadFileRequest
	6,  // 2: dfs.MasterTracker.GetFileList:input_type -> dfs.GetFileListRequest
	8,  // 3: dfs.MasterTracker.Heartbeat:input_type -> dfs.HeartbeatRequest
	10, // 4: dfs.MasterTracker.RegisterDataKeeper:input_type -> dfs.RegisterDataKeeperRequest
	12, // 5: dfs.MasterTracker.FileUploaded:input_type -> dfs.FileUploadedRequest
	14, // 6: dfs.MasterTracker.GetUploadDataKeeper:input_type -> dfs.GetUploadDataKeeperRequest
	4,  // 7: dfs.DataKeeper.FileTransfer:input_type -> dfs.FileTransferRequest
	16, // 8: dfs.DataKeeper.GetFile:input_type -> dfs.GetFileRequest
	18, // 9: dfs.DataKeeper.ReplicateFile:input_type -> dfs.ReplicateFileRequest
	1,  // 10: dfs.MasterTracker.UploadFile:output_type -> dfs.UploadFileResponse
	3,  // 11: dfs.MasterTracker.DownloadFile:output_type -> dfs.DownloadFileResponse
	7,  // 12: dfs.MasterTracker.GetFileList:output_type -> dfs.GetFileListResponse
	9,  // 13: dfs.MasterTracker.Heartbeat:output_type -> dfs.HeartbeatResponse
	11, // 14: dfs.MasterTracker.RegisterDataKeeper:output_type -> dfs.RegisterDataKeeperResponse
	13, // 15: dfs.MasterTracker.FileUploaded:output_type -> dfs.FileUploadedResponse
	15, // 16: dfs.MasterTracker.GetUploadDataKeeper:output_type -> dfs.GetUploadDataKeeperResponse
	5,  // 17: dfs.DataKeeper.FileTransfer:output_type -> dfs.FileTransferResponse
	17, // 18: dfs.DataKeeper.GetFile:output_type -> dfs.GetFileResponse
	5,  // 19: dfs.DataKeeper.ReplicateFile:output_type -> dfs.FileTransferResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
